export const WORDLIST = {
  
  //UMUR
  UMUR_1 : 'USIA',
  UMUR_2 : 'UMUR',

  //KULIAH
  EDUCATION_1 : 'STUDI',
  EDUCATION_2 : 'JURUSAN',
  EDUCATION_3 : 'KULIAH',

  //LAHIR
  LAHIR_1 : 'LAHIR',

  SKILL_1 : 'JAGO APA',

  EXPERIENCE_1 : 'PENGALAMAN KERJA',
  EXPERIENCE_2 : 'PENGALAMAN APA',
  EXPERIENCE_3 : 'KERJA DIMANA',
  EXPERIENCE_4 : 'KERJA MANA',
  EXPERIENCE_5 : 'PERNAH KERJA',

  POO_1: 'TAI',
  POO_2: 'TAI LU',
  POO_3: 'TAIK LU',

  CHIPMUNK_1: 'CHIPMUNK',

  CONTACT_1: 'CONTACT',
  CONTACT_2: 'EMAIL',
  CONTACT_3: 'INSTAGRAM',
  CONTACT_4: 'SOCIAL MEDIA',


}