export const WORDLIST = {
  
  //UMUR
  UMUR_1 : 'USIA',
  UMUR_2 : 'UMUR',

  //KULIAH
  KULIAH_1 : 'STUDI',
  KULIAH_2 : 'JURUSAN',
  KULIAH_3 : 'KULIAH',

  //LAHIR
  LAHIR_1 : 'LAHIR',

  SKILL_1 : 'JAGO APA',

  EXPERIENCE_1 : 'PENGALAMAN KERJA',
  EXPERIENCE_1 : 'PENGALAMAN APA',
  EXPERIENCE_2 : 'KERJA DIMANA',
  EXPERIENCE_2 : 'KERJA MANA',
  EXPERIENCE_3 : 'PERNAH KERJA',

  POO_1: 'TAI',
  POO_2: 'TAI LU',
  POO_3: 'TAIK LU',

  CHIPMUNK_1: 'CHIPMUNK'


}